
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives
  Tags: /tags

# Miscelaneous
favicon: /favicon.ico

# avatar
avatar: /images/avatar.jpg

# social
social:
  github: "https://github.com/markyong"
  weibo: "#"

# stylesheets loaded in the <head>
stylesheets:
- /lib/font-awesome/css/font-awesome.min.css
- /css/stage.css
- /css/avatar-bg.css

# scripts loaded in the end of the body
scripts:
- /lib/js/jquery.min.js
- /lib/js/in-view.js
- /js/waterrippleeffect.min.js
- /js/cav.js
- /js/stage.js
